### PR TITLE
First commit

### PR DESCRIPTION
**Pull request by ubergeekseven**

### CODE REVIEW

**Comment by ubergeekseven** [comment]
Changing some of the code to expose more variables in the inspector as well as making more generic variables for use in multiple ways.

**Comment by Hantoo** [comment]
Thanks!

**Comment by Hantoo** [comment]
Can't merge as FirstCommit branch has been deleted

**Comment by ubergeekseven** [comment]
Sorry, I didn't want to merge with yours because I'm messing around with everything and attempting to extend and update as much as I can. Also, I didn't want your base code to be messed up and didn't realize I had your repository as the upload setting in visual studio. I removed it as fast as possible and then started a separate repo for my code. If you want it, that's great. I just made it work for 2020 unity, exposed more variables to the inspector like password and username. I haven't yet got ssl working because I cannot get self signed certs working with the clients in using (paho based). 
Also, I can't figure out the purpose of having subscriptions on the mqtttest script. I removed the string entries in the inspector and everything still worked. If you used them, what for?
I instead use that script to connect. Then I extended the routing script to have string and boolean entries to trigger based off of matched strings. I can now switch scenes and settings from my client. It's all for remotely controlling a projection mapping setup in working on. Your code has helped lots though

**Pull request closed without merging**
